services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=inning_log'
      - 'POSTGRES_PASSWORD=inning_password'
      - 'POSTGRES_USER=inning_user'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U inning_user -d inning_log']
      interval: 10s
      timeout: 5s
      retries: 5
