-- noinspection SqlNoDataSourceInspection
create table user_push_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    platform varchar(20) not null check (platform in ('IOS', 'ANDROID', 'WEB')),
    device_id varchar(255) not null,
    push_token varchar(500) not null,
    enabled boolean not null default true,
    last_seen_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_user_push_tokens_push_token unique (push_token),
    constraint uk_user_push_tokens_user_device unique (user_id, device_id),
    constraint fk_user_push_tokens_user foreign key (user_id) references app_users (id)
);

create index idx_user_push_tokens_user_enabled
    on user_push_tokens (user_id, enabled);
