-- noinspection SqlNoDataSourceInspection
alter table user_push_tokens
    drop constraint uk_user_push_tokens_user_device;

-- V10 allowed the same installation identifier under different users. Keep the
-- most recently active owner before enforcing installation-level ownership.
delete from user_push_tokens
where id in (
    select id
    from (
        select id,
               row_number() over (
                   partition by device_id
                   order by last_seen_at desc, enabled desc, id desc
               ) as duplicate_rank
        from user_push_tokens
    ) ranked_tokens
    where duplicate_rank > 1
);

alter table user_push_tokens
    add constraint uk_user_push_tokens_device unique (device_id);

create table push_registration_locks (
    id smallint primary key,
    name varchar(50) not null unique
);

insert into push_registration_locks (id, name)
values (1, 'GLOBAL_PUSH_REGISTRATION');

create table notification_outbox (
    id bigint generated by default as identity primary key,
    idempotency_key varchar(200) not null,
    user_id bigint not null,
    notification_type varchar(50) not null check (notification_type in (
        'FRIEND_REQUEST',
        'FRIEND_ACCEPTED',
        'TIMELINE_COMMENT',
        'TIMELINE_REACTION',
        'GAME_INNING_STARTED',
        'GAME_INNING_ENDED',
        'GAME_SCORE_CHANGED',
        'RECORD_REMINDER',
        'GENERATED_VIDEO_READY',
        'GENERATED_VIDEO_FAILED'
    )),
    title varchar(100) not null,
    body varchar(500),
    data_json text not null,
    status varchar(40) not null check (status in (
        'PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_FAILURES'
    )),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    completed_at timestamp(6) with time zone,
    version bigint not null default 0,
    constraint uk_notification_outbox_user_idempotency unique (user_id, idempotency_key),
    constraint fk_notification_outbox_user foreign key (user_id) references app_users (id)
);

create index idx_notification_outbox_status_created
    on notification_outbox (status, created_at);

create table notification_delivery_targets (
    id bigint generated by default as identity primary key,
    outbox_id bigint not null,
    push_registration_id bigint not null,
    status varchar(30) not null check (status in (
        'PENDING', 'PROCESSING', 'RETRY', 'SENT', 'INVALID', 'DEAD', 'CANCELLED_OWNERSHIP'
    )),
    attempt_count integer not null default 0,
    next_attempt_at timestamp(6) with time zone not null,
    claim_token varchar(36),
    last_error_code varchar(80),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    sent_at timestamp(6) with time zone,
    version bigint not null default 0,
    constraint uk_notification_target_outbox_registration
        unique (outbox_id, push_registration_id),
    constraint fk_notification_target_outbox
        foreign key (outbox_id) references notification_outbox (id) on delete cascade
);

create index idx_notification_target_ready
    on notification_delivery_targets (status, next_attempt_at, id);

create index idx_notification_target_outbox_status
    on notification_delivery_targets (outbox_id, status);
