-- noinspection SqlNoDataSourceInspection
create table friendships (
    id bigint generated by default as identity primary key,
    requester_id bigint not null,
    receiver_id bigint not null,
    pair_key varchar(100) not null,
    status varchar(20) not null default 'PENDING',
    request_revision integer not null default 1,
    requested_at timestamp(6) with time zone not null,
    responded_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    version bigint not null default 0,
    constraint uk_friendships_pair_key unique (pair_key),
    constraint fk_friendships_requester
        foreign key (requester_id) references app_users (id),
    constraint fk_friendships_receiver
        foreign key (receiver_id) references app_users (id),
    constraint chk_friendships_not_self check (requester_id <> receiver_id),
    constraint chk_friendships_status check (status in ('PENDING', 'ACCEPTED', 'REJECTED')),
    constraint chk_friendships_request_revision check (request_revision >= 1),
    constraint chk_friendships_response_state check (
        (status = 'PENDING' and responded_at is null)
        or (status in ('ACCEPTED', 'REJECTED') and responded_at is not null)
    ),
    constraint chk_friendships_pair_key check (
        pair_key =
            cast(case when requester_id < receiver_id then requester_id else receiver_id end as varchar)
            || ':' ||
            cast(case when requester_id > receiver_id then requester_id else receiver_id end as varchar)
    )
);

create index idx_friendships_receiver_status_requested
    on friendships (receiver_id, status, requested_at desc);

create index idx_friendships_requester_status_requested
    on friendships (requester_id, status, requested_at desc);
