-- noinspection SqlNoDataSourceInspection
create table notification_settings (
    user_id bigint primary key,
    game_progress_enabled boolean not null default true,
    record_reminder_enabled boolean not null default true,
    social_reaction_enabled boolean not null default true,
    updated_at timestamp(6) with time zone not null,
    constraint fk_notification_settings_user foreign key (user_id) references app_users (id)
);

create table notifications (
    id bigint generated by default as identity primary key,
    event_key varchar(200) not null,
    user_id bigint not null,
    notification_type varchar(50) not null check (notification_type in (
        'FRIEND_REQUEST',
        'FRIEND_ACCEPTED',
        'TIMELINE_COMMENT',
        'TIMELINE_REACTION',
        'GAME_INNING_STARTED',
        'GAME_INNING_ENDED',
        'GAME_SCORE_CHANGED',
        'RECORD_REMINDER',
        'GENERATED_VIDEO_READY',
        'GENERATED_VIDEO_FAILED'
    )),
    title varchar(100) not null,
    body varchar(500),
    data_json text not null,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    constraint uk_notifications_user_event unique (user_id, event_key),
    constraint fk_notifications_user foreign key (user_id) references app_users (id)
);

create index idx_notifications_user_id_desc
    on notifications (user_id, id desc);

create index idx_notifications_user_unread
    on notifications (user_id, read_at, id);

alter table notification_outbox
    add column notification_id bigint;

-- Preserve rows created by an earlier server version and give every queued push
-- the inbox notification id that clients receive in the FCM data payload.
insert into notifications (
    event_key,
    user_id,
    notification_type,
    title,
    body,
    data_json,
    created_at
)
select idempotency_key,
       user_id,
       notification_type,
       title,
       body,
       data_json,
       created_at
  from notification_outbox;

update notification_outbox
   set notification_id = (
       select notifications.id
         from notifications
        where notifications.user_id = notification_outbox.user_id
          and notifications.event_key = notification_outbox.idempotency_key
   );

alter table notification_outbox
    alter column notification_id set not null;

alter table notification_outbox
    add constraint uk_notification_outbox_notification unique (notification_id);

alter table notification_outbox
    add constraint fk_notification_outbox_notification
        foreign key (notification_id) references notifications (id);
