create table games (
    id bigint generated by default as identity primary key,
    season_year integer not null check (season_year between 1900 and 9999),
    game_type varchar(30) not null check (game_type in ('UNKNOWN','REGULAR','EXHIBITION','WILDCARD','SEMI_PLAYOFF','PLAYOFF','KOREAN_SERIES')),
    game_date date not null,
    game_sequence smallint check (game_sequence in (0,1,2)),
    scheduled_at timestamp(6) with time zone,
    started_at timestamp(6) with time zone,
    ended_at timestamp(6) with time zone,
    home_team_id bigint not null references kbo_teams(id),
    away_team_id bigint not null references kbo_teams(id),
    stadium_name_snapshot varchar(100),
    home_score integer check (home_score >= 0),
    away_score integer check (away_score >= 0),
    status varchar(20) not null check (status in ('UNKNOWN','SCHEDULED','LIVE','FINISHED','CANCELED','POSTPONED','DELAYED','SUSPENDED')),
    current_inning integer check (current_inning >= 1),
    current_half varchar(6) check (current_half in ('TOP','BOTTOM')),
    schedule_observed_at timestamp(6) with time zone not null,
    result_observed_at timestamp(6) with time zone not null,
    result_source varchar(20) not null check (result_source in ('SCHEDULE','SCOREBOARD')),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint chk_games_different_teams check (home_team_id <> away_team_id),
    constraint chk_games_inning_pair check ((current_inning is null) = (current_half is null)),
    constraint uq_games_schedule unique (game_date, home_team_id, away_team_id, game_sequence, game_type)
);
create index idx_games_date on games(game_date);
create index idx_games_home_date on games(home_team_id, game_date);
create index idx_games_away_date on games(away_team_id, game_date);

create table game_external_ids (
    id bigint generated by default as identity primary key,
    game_id bigint not null references games(id),
    provider varchar(20) not null check (provider = 'KBO'),
    external_id varchar(100) not null,
    created_at timestamp(6) with time zone not null,
    constraint uq_game_external_provider_id unique(provider, external_id),
    constraint uq_game_external_game_provider unique(game_id, provider)
);

create table user_game_logs (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id),
    game_id bigint not null references games(id),
    cheering_team_id bigint not null references kbo_teams(id),
    viewing_type varchar(10) not null check (viewing_type in ('STADIUM','HOME')),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uq_user_game_logs_user_game unique(user_id, game_id)
);
create index idx_user_game_logs_viewing on user_game_logs(user_id, viewing_type, deleted_at, game_id);
create index idx_user_game_logs_game_user on user_game_logs(game_id, user_id);

-- A single DB lock serializes the small KBO import workload, including inserts
-- for schedules that do not have an external ID yet. It works across instances.
create table game_import_lock (id integer primary key check (id = 1));
insert into game_import_lock(id) values (1);

create table game_snapshot_receipts (
    event_key varchar(64) primary key,
    source varchar(30) not null,
    observed_at timestamp(6) with time zone not null,
    processed_at timestamp(6) with time zone not null
);

create table game_sync_scopes (
    scope_key varchar(30) primary key,
    state varchar(15) not null check (state in ('IMPORTED','PARTIAL')),
    observed_at timestamp(6) with time zone not null,
    last_applied_at timestamp(6) with time zone not null
);
