create table inning_records (
    id bigint generated by default as identity primary key,
    user_game_log_id bigint not null references user_game_logs(id),
    client_record_id varchar(36) not null,
    request_fingerprint varchar(64) not null,
    inning_number integer not null check (inning_number between 1 and 99),
    half varchar(6) check (half in ('TOP', 'BOTTOM')),
    caption varchar(255) not null,
    recorded_at timestamp(6) with time zone not null,
    home_score_at_recording integer check (home_score_at_recording >= 0),
    away_score_at_recording integer check (away_score_at_recording >= 0),
    score_observed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    deleted_at timestamp(6) with time zone,
    constraint uq_inning_records_client unique(user_game_log_id, client_record_id),
    constraint chk_inning_record_score_pair check (
        (home_score_at_recording is null) = (away_score_at_recording is null)
        and (home_score_at_recording is null) = (score_observed_at is null))
);
-- Several clips in the same inning/half are separate records, ordered by capture time.
create index idx_inning_records_timeline
    on inning_records(user_game_log_id, deleted_at, inning_number, recorded_at, id);
