create table game_state_snapshots (
    id bigint generated by default as identity primary key,
    game_id bigint not null references games(id) on delete cascade,
    status varchar(20) not null check (status in ('UNKNOWN','SCHEDULED','LIVE','FINISHED','CANCELED','POSTPONED','DELAYED','SUSPENDED')),
    current_inning integer check (current_inning >= 1),
    current_half varchar(6) check (current_half in ('TOP','BOTTOM')),
    home_score integer check (home_score >= 0),
    away_score integer check (away_score >= 0),
    observed_at timestamp(6) with time zone not null,
    result_source varchar(20) not null check (result_source in ('SCHEDULE','SCOREBOARD')),
    created_at timestamp(6) with time zone not null,
    constraint chk_game_state_snapshot_inning_pair check ((current_inning is null) = (current_half is null))
);

create index idx_game_state_snapshots_timeline
    on game_state_snapshots(game_id, observed_at, id);

-- Existing games cannot recover past transitions, but retaining their latest trusted
-- state establishes a safe baseline for all changes observed after this migration.
insert into game_state_snapshots(
    game_id, status, current_inning, current_half, home_score, away_score,
    observed_at, result_source, created_at)
select id, status, current_inning, current_half, home_score, away_score,
       result_observed_at, result_source, updated_at
  from games;
