-- noinspection SqlNoDataSourceInspection
create table app_users (
    id bigint generated by default as identity primary key,
    email varchar(320) not null,
    nickname varchar(80),
    profile_image_url varchar(500),
    role varchar(30) not null check (role in ('USER')),
    onboarding_completed boolean not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

create table oauth_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    provider varchar(30) not null check (provider in ('GOOGLE')),
    provider_user_id varchar(120) not null,
    email varchar(320) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_oauth_accounts_provider_provider_user_id unique (provider, provider_user_id),
    constraint fk_oauth_accounts_user foreign key (user_id) references app_users (id)
);
