-- noinspection SqlNoDataSourceInspection
create table kbo_teams (
    id bigint generated by default as identity primary key,
    team_code varchar(10) not null,
    name varchar(50) not null,
    short_name varchar(20) not null,
    logo_url varchar(500),
    primary_color varchar(20),
    home_stadium_id bigint,
    display_order integer not null,
    active boolean not null default true,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint uk_kbo_teams_team_code unique (team_code),
    constraint uk_kbo_teams_name unique (name)
);

create index idx_kbo_teams_display_order on kbo_teams (display_order);
create index idx_kbo_teams_active on kbo_teams (active);

insert into kbo_teams (
    team_code,
    name,
    short_name,
    logo_url,
    primary_color,
    home_stadium_id,
    display_order,
    active,
    created_at,
    updated_at
)
values
    ('NC', 'NC Dinos', 'NC', null, null, null, 1, true, current_timestamp, current_timestamp),
    ('LG', 'LG Twins', 'LG', null, null, null, 2, true, current_timestamp, current_timestamp),
    ('OB', 'Doosan Bears', 'Doosan', null, null, null, 3, true, current_timestamp, current_timestamp),
    ('KT', 'KT Wiz', 'KT', null, null, null, 4, true, current_timestamp, current_timestamp),
    ('SS', 'Samsung Lions', 'Samsung', null, null, null, 5, true, current_timestamp, current_timestamp),
    ('WO', 'Kiwoom Heroes', 'Kiwoom', null, null, null, 6, true, current_timestamp, current_timestamp),
    ('HH', 'Hanwha Eagles', 'Hanwha', null, null, null, 7, true, current_timestamp, current_timestamp),
    ('HT', 'KIA Tigers', 'KIA', null, null, null, 8, true, current_timestamp, current_timestamp),
    ('SK', 'SSG Landers', 'SSG', null, null, null, 9, true, current_timestamp, current_timestamp),
    ('LT', 'Lotte Giants', 'Lotte', null, null, null, 10, true, current_timestamp, current_timestamp);
