-- noinspection SqlNoDataSourceInspection
create table stadiums (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    city varchar(50) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null
);

alter table kbo_teams
    add constraint fk_kbo_teams_home_stadium
    foreign key (home_stadium_id) references stadiums (id);
