-- noinspection SqlNoDataSourceInspection
alter table app_users add column deleted_at timestamp(6) with time zone;
alter table app_users add column version bigint not null default 0;

create table auth_refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash char(64) not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    last_used_at timestamp(6) with time zone,
    generation integer not null default 1,
    created_at timestamp(6) with time zone not null,
    constraint uk_auth_refresh_tokens_token_hash unique (token_hash),
    constraint chk_auth_refresh_tokens_generation check (generation >= 1),
    constraint fk_auth_refresh_tokens_user foreign key (user_id) references app_users (id)
);

create index idx_auth_refresh_tokens_user_expiry
    on auth_refresh_tokens (user_id, expires_at);

create index idx_auth_refresh_tokens_expiry
    on auth_refresh_tokens (expires_at);

create index idx_auth_refresh_tokens_user_active
    on auth_refresh_tokens (user_id, revoked_at);
